<?php

header('Content-Type: application/json');

function respond_json($status, $payload){
	http_response_code($status);
	echo json_encode($payload);
	exit;
}

function delete_dir_recursive($dir){
	if(! is_dir($dir)){
		return true;
	}

	$items = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS),
		RecursiveIteratorIterator::CHILD_FIRST
	);

	foreach ($items as $item){
		if($item->isDir()){
			rmdir($item->getRealPath());
		} else{
			unlink($item->getRealPath());
		}
	}

	return rmdir($dir);
}

$name = strtolower(trim($_POST['name'] ?? ''));

if($name === ''){
	respond_json(400, ['status' => 'error', 'message' => 'Missing cup slug.']);
}

if(! preg_match('/^[a-z0-9_]+$/', $name)){
	respond_json(400, ['status' => 'error', 'message' => 'Invalid cup slug.']);
}

$dataDir = __DIR__;
$cupsDir = $dataDir . '/gamemaster/cups';
$cupPath = $cupsDir . '/' . $name . '.json';

if(! file_exists($cupPath)){
	respond_json(404, ['status' => 'error', 'message' => 'Cup file not found.']);
}

// Remove cup file
if(! unlink($cupPath)){
	respond_json(500, ['status' => 'error', 'message' => 'Failed to delete cup file.']);
}

// Update formats.json (remove all entries for this cup)
$formatsPath = $dataDir . '/gamemaster/formats.json';
$formatsRaw = file_get_contents($formatsPath);
if($formatsRaw === false){
	respond_json(500, ['status' => 'error', 'message' => 'Failed to read formats.json.']);
}

$formats = json_decode($formatsRaw, true);
if(! is_array($formats)){
	respond_json(500, ['status' => 'error', 'message' => 'formats.json is invalid.']);
}

$formats = array_values(array_filter($formats, function($format) use ($name){
	return ($format['cup'] ?? '') !== $name;
}));

if(file_put_contents($formatsPath, json_encode($formats, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)) === false){
	respond_json(500, ['status' => 'error', 'message' => 'Failed to write formats.json.']);
}

// Delete rankings directory for this cup
$rankingsDir = $dataDir . '/rankings/' . $name;
delete_dir_recursive($rankingsDir);

// Rebuild gamemaster.json, gamemaster.min.json, and formats.php
$base = json_decode(file_get_contents($dataDir . '/gamemaster/base.json'), true);
$pokemon = json_decode(file_get_contents($dataDir . '/gamemaster/pokemon.json'), true);
$moves = json_decode(file_get_contents($dataDir . '/gamemaster/moves.json'), true);

if(! is_array($base) || ! is_array($pokemon) || ! is_array($moves)){
	respond_json(500, ['status' => 'error', 'message' => 'Gamemaster source files are invalid.']);
}

$base['timestamp'] = date('Y-m-d H:i:s', time());
$base['pokemon'] = $pokemon;
$base['moves'] = $moves;
$base['formats'] = $formats;
$base['cups'] = [];

$dir = new DirectoryIterator($cupsDir);
foreach ($dir as $file) {
	if ($file->getExtension() === 'json') {
		$cup = json_decode(file_get_contents($cupsDir . '/' . $file->getFilename()), true);
		if(! is_null($cup)){
			$base['cups'][] = $cup;
		}
	}
}

$gmJson = json_encode($base, JSON_UNESCAPED_SLASHES);
if($gmJson === false){
	respond_json(500, ['status' => 'error', 'message' => 'Failed to encode gamemaster.json.']);
}

if(file_put_contents($dataDir . '/gamemaster.json', $gmJson) === false){
	respond_json(500, ['status' => 'error', 'message' => 'Failed to write gamemaster.json.']);
}

if(file_put_contents($dataDir . '/gamemaster.min.json', $gmJson) === false){
	respond_json(500, ['status' => 'error', 'message' => 'Failed to write gamemaster.min.json.']);
}

$formatContent = '<?php' . "\n";
$formatContent .= '// This file is generated by custom-cup-delete.php. Do not edit directly.' . "\n";
$formatContent .= '$formats = ' . var_export($formats, true) . ';' . "\n";
$formatContent .= '?>';

if(file_put_contents($dataDir . '/formats.php', $formatContent) === false){
	respond_json(500, ['status' => 'error', 'message' => 'Failed to write formats.php.']);
}

respond_json(200, [
	'status' => 'success',
	'cup' => $name
]);
