<?php
// This file is generated by compile.php. Do not edit directly.
$formats = array (
  0 => 
  array (
    'title' => 'P!P Championship Series',
    'cup' => 'championshipseries',
    'cp' => 1500,
    'meta' => 'championshipseries',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'hideRankings' => true,
  ),
  1 => 
  array (
    'title' => 'Mega Great League',
    'cup' => 'mega',
    'cp' => 1500,
    'meta' => 'megagreat',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'Pokémon must be at or below 1,500 CP to enter.',
      1 => 'Mega Evolutions are eligible.',
    ),
  ),
  2 => 
  array (
    'title' => 'Mega Ultra League',
    'cup' => 'mega',
    'cp' => 2500,
    'meta' => 'megaultra',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'Pokémon must be at or below 2,500 CP to enter.',
      1 => 'Mega Evolutions are eligible.',
    ),
  ),
  3 => 
  array (
    'title' => 'Mega Master League',
    'cup' => 'mega',
    'cp' => 10000,
    'meta' => 'mega',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'No CP limit.',
      1 => 'Mega Evolutions are eligible.',
    ),
  ),
  4 => 
  array (
    'title' => 'Master Premier Cup',
    'cup' => 'premier',
    'cp' => 10000,
    'meta' => 'premiermaster',
    'showCup' => true,
    'showFormat' => false,
    'showMeta' => true,
    'hideRankings' => true,
    'rules' => 
    array (
      0 => 'No CP limit.',
      1 => 'Legendary Pokémon, Mythical Pokémon, and Ultra Beasts are not eligible.',
    ),
  ),
  5 => 
  array (
    'title' => 'Battle Frontier (Coupe du Sillage)',
    'cup' => 'coupedusillage',
    'cp' => 10000,
    'meta' => 'coupedusillage',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
  ),
  6 => 
  array (
    'title' => 'BF ML',
    'cup' => 'bf_ml',
    'cp' => 10000,
    'meta' => 'master',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => true,
    'rules' => 
    array (
      0 => 'Mega Evolutions are eligible.',
      1 => 'Shadow Pokémon are eligible.',
    ),
  ),
  7 => 
  array (
    'title' => 'Little Cup',
    'cup' => 'little',
    'cp' => 500,
    'meta' => 'little',
    'showCup' => false,
    'showFormat' => false,
    'showMeta' => false,
  ),
  8 => 
  array (
    'title' => 'Catch Cup',
    'cup' => 'catch',
    'cp' => 1500,
    'meta' => 'great',
    'showCup' => false,
    'showFormat' => false,
    'showMeta' => false,
  ),
  9 => 
  array (
    'title' => 'Custom',
    'cup' => 'custom',
    'cp' => 1500,
    'meta' => 'great',
    'showCup' => true,
    'showFormat' => true,
    'showMeta' => false,
  ),
);
?>